### ISSUE TITLE
How to get the optimization results?

### ISSUE THREAD

**Issue by wenjinghu** [tsinghua-fib-lab/G2DBP#1]
老师您好，谢谢您的精彩工作！
我想请教一个问题，在运行run_ours.py后，得到了results文件夹里的.pkl文件，请问这个结果应该如何查看呢？针对一个确定的group，怎么知道这个group使用的Bin的数量呢？ @John-Ao

**Comment by John-Ao** [comment]
我添加了demo.ipynb，在里面展示了如何使用我们的模型得到优化结果，希望能解决你的问题。

---

I have added [demo.ipynb](../blob/master/demo.ipynb), where I demonstrate how to use the datasets and how to use our pretrained models to obtain the optimization results.

**Comment by wenjinghu** [comment]
超级感谢老师！老师的demo特别详细，我终于弄懂了~
